apiVersion: apps/v1
kind: Deployment
metadata:
  name: mbadevops-vendedor-deploy
  labels:
    app: mbadevops-vendedor
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: mbadevops-vendedor
  template:
    metadata:
      name: mbadevops-vendedor-deploy
      labels:
        app: mbadevops-vendedor
    spec:
      restartPolicy: Always
      containers:
      - name: mbadevops-vendedor
        imagePullPolicy: Always
        image: marciopinheiro/mba-devops:latest
        ports:
        - name: default-port
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /health-check/
            port: default-port
          initialDelaySeconds: 0
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /health-check/
            port: default-port
          initialDelaySeconds: 0
          periodSeconds: 60
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - name: mbadevops-logs-pvc
          mountPath: /var/www/logs
        env:
        - name: FLASK_APP
          value: "mbadevops-vendedor"
        - name: FLASK_ENV
          value: "production"
        - name: FLASK_DEBUG
          value: "0"
        - name: REDIS_HOST
          value: "10.98.51.21"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
      volumes:
      - name: mbadevops-logs-pvc
        persistentVolumeClaim:
          claimName: mbadevops-logs-pvc
