apiVersion: v1
kind: Service
metadata:
  name: redis-srv
  labels:
    service: redis-srv
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
